### ISSUE TITLE
Traceback: Last Day

### ISSUE THREAD

**Issue by MamdAldhahri** [HelloThereMatey/Plebs_Macro#2]
royalworldtech@Royals-MacBook-Pro NetLiquidity % python3 ShowNetLiq.py
/Users/royalworldtech/Documents/Trading/Plebs_Macro/NetLiquidity /Users/royalworldtech/Documents/Trading/Plebs_Macro
System information:  darwin mac , directory delimiter:  / , working directory:  /Users/royalworldtech/Documents/Trading/Plebs_Macro/NetLiquidity
FRED API key:  e57e3df135e58489bd29650f14b72c4a , Save FRED data to:  /Users/royalworldtech/Documents/Trading/Plebs_Macro/NetLiquidity/FRED_Data
FRED data series to pull:  ['WALCL', 'RRPONTSYD', 'WTREGEN', 'RESPPNTNWW', ('WRESBAL', 'yes')]
Data start from input file:  2023-05-01 00:00:00 , end:  2023-08-01 00:00:00
Pulling data for date range:  2023-05-01  to  2023-08-01 , number of days:  92
Start date: 2023-05-01 , end date:  2023-08-01
First day in TGA data:  2005-10-03 Last day in TGA data:  2023-09-14 , Length of data:  4534 . Date range:  6555
Getting new data for the TGA from Treasury to update the TGA data excel file, please wait............
cannot access local variable 'NextDSStarT' where it is not associated with a value
Exception, may be at end of data or those cunts changed the names in the table or sumtin, have a few more tries & then pull out.
Traceback (most recent call last):
  File "/Users/royalworldtech/Documents/Trading/Plebs_Macro/NetLiquidity/ShowNetLiq.py", line 144, in <module>
    CheckData2 = PriceImporter.PullTGA_Data(AccountName = 'Treasury General Account (TGA) Closing Balance',start_date=LastDate)   #Check the latest data from treasury.
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/royalworldtech/Documents/Trading/Plebs_Macro/MacroBackend/PriceImporter.py", line 416, in PullTGA_Data
    LastSetFinDay = LastDay
                    ^^^^^^^
UnboundLocalError: cannot access local variable 'LastDay' where it is not associated with a value

**Comment by HelloThereMatey** [comment]
I fixed that issue a while back. Did you update repo and run scripts again?
